paths:
  raw: "../../data/1. raw/"
  placed: "../../data/2. placed/"
  labelled: "../../data/3. labelled/"
  preprocessed: "../../data/4. preprocessed/"
  repeated: "../../data/5. repeated/"
  compared: "../../data/6. compared/"
  base_prompt: "../base_prompt/"
  node: "../node-roguelike/"



